### ISSUE TITLE
Curve.java

### ISSUE THREAD

**Issue by rafriofra** [EGC-1617/Verificacion-G1#1]
Cuando he borrado el archivo Curve.java ha producido errores en los siguientes archivos: CryptoEngine.java, PointGMP.java, WeierStrassCurve.java

Prioridad Alta

**Comment by jesnavino** [comment]
Creo que lo que hace falta es borrar los importes que hacen referencia a las clases borradas #1

**Comment by rafriofra** [comment]
Se ha subido una nueva versión adaptada a nuestras exigencias, quedando solucionada la incidencia.
