### ISSUE TITLE
Crear método para encriptar y desencriptar.

### ISSUE THREAD

**Issue by ernrodnun** [EGC-1617/Verificacion-G1#15]
Crear un método para que en un simple llamada, nos devuelva el texto encriptado y la comprobación de que al desecriptarlo se corresponde con el texto sin encriptar.

**Comment by mrufpal** [comment]
Commit: df198653d31d1f1c28ffd610cb51e4a68fd2c8c8

**Comment by mrufpal** [comment]
Revisado
