### ISSUE TITLE
Creación de test que compruebe que las claves no se cree vacias

### ISSUE THREAD

**Issue by josruinav** [EGC-1617/Verificacion-G1#3]
Creación de un test que compruebe que al crear las claves tanto publica como privada no las cree vacias.

Prioridad : Media

**Comment by rafriofra** [comment]
El test ha sido creado y comprobado, y queda pendiente de revisión.

El commit asociado ha dicha issue es: c415b4ecf670406635af8d2d86878a26b687f723

El compañero @josruinav  verificará que funciona correctamente.

**Comment by josruinav** [comment]
Ha sido comprobada la incidencia.
