### ISSUE TITLE
Realizar pruebas en local

### ISSUE THREAD

**Issue by rafriofra** [EGC-1617/Verificacion-G1#6]
Realizar pruebas en local.

**Comment by jesnavino** [comment]
Realizados todos los test en local de la aplicación. Esperando revisión por parte de @rafriofra .

Los commits asociados a los test son los siguientes:

5d8e0e7c853f593b30eb8b903aab082daf8c0200
3f7affc2921f4bb3caa97e233b5c6f4f299e4627
e91b0f1a80f259088e5ac568d0ed62d532266913
33088bff5438d36f4bbfa70dafffc23aa0eecb79
cf620a5d32e45e4d4a5510ab7b1abc0e61e77ae0
ead86a7a985157182fccc39d3b125c40d8e7776d
94d4be83bb08e72e340c5909c2743e966c0a0cf4

**Comment by rafriofra** [comment]
Los test en local han sido revisados.
