### ISSUE TITLE
Mejorar el aspecto de la interfaz gráfica

### ISSUE THREAD

**Issue by rafriofra** [EGC-1617/Verificacion-G1#8]
Facilitar la comunicación entre el programa y el usuario, mostrando descripciones de las tareas realizadas y otros.

**Comment by rafriofra** [comment]
El encargado de mejorar la interfaz ha sido @josruinav  y se encargará de revisarla @jesnavino

**Comment by jesnavino** [comment]
Interfaz grafica revisada y funcionando correctamente.
